apiVersion: v1
kind: Pod
metadata:
  name: express-app
  labels:
    name: express-app
spec:
  containers:
  - name: express-app
    image: express-app
    ports:
    - containerPort: 3000
    imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Pod
metadata:
  name: react-app
  labels:
    name: react-app
spec:
  containers:
  - name: react-app
    image: react-app
    ports:
    - containerPort: 3001
    imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: express-app
spec:
  type: LoadBalancer
  ports:
  - port: 3000
  selector:
    name: express-app
---
apiVersion: v1
kind: Service
metadata:
  name: react-app
spec:
  type: LoadBalancer
  ports:
  - port: 3001
  selector:
    name: react-app
